#ifndef MULTICASTTUNNELSERVER_H

#define MULTICASTTUNNELSERVER_H

#define MCASTTUNNEL_CHANNEL_CONTROL			0
#define MCASTTUNNEL_CHANNEL_DATA			1

#define MCASTTUNNEL_COMMAND_PORT			1
#define MCASTTUNNEL_COMMAND_ACK				2
#define MCASTTUNNEL_COMMAND_ACKERR			3
#define MCASTTUNNEL_COMMAND_START			4
#define MCASTTUNNEL_COMMAND_JOIN			5
#define MCASTTUNNEL_COMMAND_LEAVE			6
	
#endif // MULTICASTTUNNELSERVER_H
